### ISSUE TITLE
Run multiple DelayedJob workers using Docker image

### ISSUE THREAD

**Issue by Toast707** [huginn/huginn#2027]
Hi, I'd like to run multiple DelayedJob workers using the docker image, would this just be passed as an environment variable? 
`docker run -it -d -p 3000:3000 -v /home/user/mysql-data:/var/lib/mysql cantino/huginn \
-e dj2: bundle exec script/delayed_job -i 2 run \
-e dj3: bundle exec script/delayed_job -i 3 run \
-e dj4: bundle exec script/delayed_job -i 4 run`

**Comment by dsander** [comment]
Hi @Toast707,

this is not possible with the `huginn/huginn` docker image, but you can switch to `huginn/signle-process` to run multiple delayed_job processes.

First stop your current Huginn container and make a backup of you mysql volume data. Then use this `docker-compose.yml` file

```yaml
# This needs at least compose 1.6.0
version: '2'

services:
  mysql:
    image: mysql:5.5
    volumes:
      - /home/user/mysql-data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: huginn_production
      MYSQL_USER: huginn
      MYSQL_PASSWORD: myhuginnpassword

  huginn_web:
    image: huginn/huginn-single-process
    restart: always
    ports:
      - 3000:3000
    links:
      - mysql
    environment:
      DATABASE_ADAPTER: mysql2
      DATABASE_NAME: huginn_production
      DATABASE_USERNAME: huginn
      DATABASE_PASSWORD: myhuginnpassword
      APP_SECRET_TOKEN: 3bd139f9186b31a85336bb89cd1a1337078921134b2f48e022fd09c234d764d3e19b018b2ab789c6e0e04a1ac9e3365116368049660234c2038dc9990513d49c
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306

  huginn_threaded:
    image: huginn/huginn-single-process
    restart: always
    links:
      - mysql
    command: /scripts/init bin/threaded.rb
    environment:
      DATABASE_ADAPTER: mysql2
      DATABASE_NAME: huginn_production
      DATABASE_USERNAME: huginn
      DATABASE_PASSWORD: myhuginnpassword
      APP_SECRET_TOKEN: 3bd139f9186b31a85336bb89cd1a1337078921134b2f48e022fd09c234d764d3e19b018b2ab789c6e0e04a1ac9e3365116368049660234c2038dc9990513d49c
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306

  huginn_dj1:
    image: huginn/huginn-single-process
    links:
      - mysql
    command: /scripts/init script/delayed_job run
    environment:
      DATABASE_ADAPTER: mysql2
      DATABASE_NAME: huginn_production
      DATABASE_USERNAME: huginn
      DATABASE_PASSWORD: myhuginnpassword
      APP_SECRET_TOKEN: 3bd139f9186b31a85336bb89cd1a1337078921134b2f48e022fd09c234d764d3e19b018b2ab789c6e0e04a1ac9e3365116368049660234c2038dc9990513d49c
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MYSQL_PORT_3306_TCP_PORT: 3306
```

Now we just start the mysql service and then create a `huginn` mysql user:
```
docker-compose start mysql
docker-compose exec mysql mysql -u root -ppassword -e "CREATE USER 'huginn'@'%' IDENTIFIED BY 'myhuginnpassword'; GRANT ALL ON huginn_production.* TO 'huginn'@'%'; FLUSH PRIVILEGES ;"
```

You can then start the all containers with `docker-compose up -d`.
