### ISSUE TITLE
[Question] Worker process containers for the single-process docker setup

### ISSUE THREAD

**Issue by zicklag** [huginn/huginn#2198]
I have a question about the single-process docker setup given in this repo. I have pretty much no understanding of ruby or the way that huginn is set up and I can't figure out whether or not the worker process containers actually connecting to the main `huginn_web` service. I don't see anything that would connect the processes to the master `huginn_web` service other than the fact that they connect to the same database. Is that enough for the worker processes to perform jobs for the master server?

Also, is it possible to scale up the `huginn_web` service container and be able to hit either of those containers on port 3000 for the web interface without causing problems?

Any insight into how this works would be very helpful.

I am using a modified version of the postgresql.yml that I intend to use in Rancher.

```yml
version: '2'

services:
  postgres:
    image: postgres:9.5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: huginn
      POSTGRES_DB: huginn
      http_proxy:
      https_proxy:
    labels:
      io.rancher.container.pull_image: always

  huginn_web:
    image: huginn/huginn-single-process
    restart: always
    ports:
      - 80:3000
    environment:
      DATABASE_ADAPTER: postgresql
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      POSTGRES_PORT_5432_TCP_PORT: 5432
      DATABASE_ADAPTER: postgresql
      DATABASE_NAME: huginn
      DATABASE_USERNAME: huginn
      DATABASE_PASSWORD: ${DB_PASSWORD}
      APP_SECRET_TOKEN: ${APP_SECRET_TOKEN}
      http_proxy:
      https_proxy:
    labels:
      io.rancher.container.pull_image: always

  huginn_threaded:
    image: huginn/huginn-single-process
    restart: always
    environment:
      DATABASE_ADAPTER: postgresql
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      POSTGRES_PORT_5432_TCP_PORT: 5432
      DATABASE_ADAPTER: postgresql
      DATABASE_NAME: huginn
      DATABASE_USERNAME: huginn
      DATABASE_PASSWORD: ${DB_PASSWORD}
      APP_SECRET_TOKEN: ${APP_SECRET_TOKEN}
      http_proxy:
      https_proxy:
    labels:
      io.rancher.container.pull_image: always
    command: /scripts/init bin/threaded.rb

volumes:
  postgres-data:
    driver: ${STORAGE_DRIVER}
```

**Comment by dsander** [comment]
> I don't see anything that would connect the processes to the master huginn_web service other than the fact that they connect to the same database. Is that enough for the worker processes to perform jobs for the master server?

That is correct.

> Also, is it possible to scale up the huginn_web service container and be able to hit either of those containers on port 3000 for the web interface without causing problems?

I did not have the need to do this before, but don't see any problems with it. The `web` container is only starting a application server which answers to HTTP requests.

It is more common to require more "delayed job" (the library used to process background jobs, run agents, etc) instances. We start one delayed job process in the `bin/threaded.rb`, when a lot of Agents are used I find it best to start delayed job in separte containers:

```yaml
  huginn_agent_runner:
    environment:
      ...
    command: /scripts/init bin/agent_runner.rb

  huginn_dj:
    environment:
      ...
    command: /scripts/init script/delayed_job run

  huginn_dj2:
    environment:
      ...
    command: /scripts/init script/delayed_job run
```
