### ISSUE TITLE
Home Assistant Agent

### ISSUE THREAD

**Issue by jjanderson** [huginn/huginn#2500]
Would it be possible to build an Agent for Home Assistant?

**Comment by degan6** [comment]
Huginn more or less has this already with the POST agent. You can post into your HA instance. 

What are you trying to accomplish?

**Comment by jjanderson** [comment]
I have created a post agent and I have a webhook automation in Home Assistant, but this does not seem to be working.

I have a webhook agent firing the post agent. The webhook agent is working but the post agent seems not to be working:

Here is the post agent:

{
  "post_url": "http://xxxxx.duckdns.org/api/webhook/26122015",
  "expected_receive_period_in_days": "4",
  "content_type": "JSON",
  "method": "post",
  "payload": {
    "key": "",
    "something": "the event contained {{ somekey }}"
  },
  "headers": {
  },
  "emit_events": "true",
  "no_merge": "true",
  "output_mode": "clean"
}

**Comment by degan6** [comment]
What part of the post agent isn't working? I plugged this agent into my instance and it looks like a standard post agent so it should work fine.

Sounds like you have a separate webhook agent that collects events and this post agent sends them to home assistant? 

Is the post agent generating events or is it erroring out where you can see something in the agent log?

Another thing to look is the webhook on HA, do you know that it is working on the HA side?

**Comment by jjanderson** [comment]
It was working in HA, but then again the upgrade to .90 could have broken this.... I had to rebuild my docker env and recreate everything in huginn again and since then it does not seem to be working...

in HA, I have the following automation:

```
- id: mobimeds_sms_counter
  alias: Mobi Meds SMS Counter
  hide_entity: false
  initial_state: 'on'
  trigger:
  - platform: webhook
    webhook_id: xxxx
  action:
  - service: counter.increment
    entity_id: counter.mobisms

```
