### ISSUE TITLE
Docker Synology

### ISSUE THREAD

**Issue by beisat** [huginn/huginn#2545]
Hi

So having spend the better part of 4h trying to get huginn running on my synology docker, I'm making this post before giving up.

Using without the exported volume or external Mysql works fine, but of course this is only for testing and not persistent.

With exporting the volume I cannot find any way to set the UID / GID (like for instance with linuxserver.io images). Without this, no matter who I make the owner of my folder in DSM, the database cannot be created as the container cannot write. (using ssh to chmod is not a solution here...)

The dockerhub description on the other hand seems quite old - the suggested centurylink / mysql hasn't been updated for 4 years... 
Using the regular mysql image, I can setup a DB. I even tried linking to huginn (though docker advises against this...), set everything as described + DATABASE_PORT 3307 (synology reserves 3306 for it's own non-docker mysql), but it always ends with

bootstrap stdout | . bootstrap stderr | ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

Can this really be so hard?

**Comment by Leosirth** [comment]
I don't have a Synology.

I'm currently using huginn with mariadb (the evolution of mysql).
After set up the mariadb container, create a new database and user.
After this you just need to add the following environment variable to huginn container:

HUGINN_DATABASE_NAME (name of your database)
HUGINN_DATABASE_USERNAME (db user)
HUGINN_DATABASE_PASSWORD (db password)
HUGINN_DATABASE_HOST (mariadb container name)

The huginn and mariadb containers needs to be on the same docker network, you can create a dedicated one.

**Comment by beisat** [comment]
bootstrap stdout | DATABASE_HOST=http://myserver.mynas
bootstrap stdout | Starting mysql server...
mysqld stderr | 190609 17:05:04 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
mysqld stdout | 190609 17:05:04 mysqld_safe Logging to '/var/log/mysql/error.log'.
mysqld stdout | 190609 17:05:04 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
bootstrap stdout | .2019-06-09 17:05:06,340 INFO exited: bootstrap (exit status 1; not expected)
bootstrap stderr | ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

I have no idea why huginn is insisting on root@localhost NO PW.

Could you provide more info? Are you using 
- docker linking (with an alias)?
- DO_NOT_CREATE_DATABASE:true
- Bridge Mode or "same Network as Host" (Passthrough)

My MySQL DB is accessible currently via http://myserver.mynas:3307 and contains a database"huginn" without tables, a user "huginn" and a "pw" as well as a "rootpw". It was created by passing the environment variables on first start of of the container. I can easily access it via phpmyadmin (also running in docker).

My huginn container has following environment variables:

HUGINN_DATABASE_NAME:huginn
HUGINN_DATABASE_USERNAME:huginn
HUGINN_DATABASE_PASSWORD:pw
HUGINN_DATABASE_HOST:http://myserver.mynas
HUGINN_DATABASE_PORT:3307
OUTDATED_DOCKER_IMAGE_NAMESPACE:false
PATH:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

The last 2 are defaults.

**Comment by Leosirth** [comment]
I'm not using linking and my network is set to bridge.

Try to set only the hostname in HUGINN_DATABASE_HOST, without "http://"

**Comment by beisat** [comment]
Ok, i'm also not using linking and set to bridge.

It's working now. a combination of switching to the IP, clearing the container changing the MySQL PW back and forth did it.

I can confirm that using http:// breaks it, not sure if something else was also messed though as the inital change didn't save it. thanks

**Comment by beisat** [comment]
So at some point while running fine for a few weeks, it must of had an issue again, and just sort of stopped working. Couldn't get it to connect anymore, until I again cleared the container. Same error as above again. Now it's running fine again...

**Comment by frumpymoons** [comment]
I have the same error. This only happens if you don't remove the container first. For example a restart causes this.

```
huginn              | bootstrap stdout | DATABASE_HOST=mariadb
huginn              | bootstrap stdout | Starting mysql server...
huginn              | mysqld stderr | 190805 02:30:52 mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
huginn              | mysqld stdout | 190805 02:30:52 mysqld_safe Logging to '/var/log/mysql/error.log'.
huginn              | mysqld stdout | 190805 02:30:52 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
huginn              | bootstrap stdout | . bootstrap stderr | ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
huginn              | 2019-08-05 02:30:54,436 INFO exited: bootstrap (exit status 1; not expected)
```
```
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb
    restart: always
    networks:
      - internal
    volumes:
      - /opt/docker/mariadb:/config
    environment:
      - PUID=1100
      - PGID=1100
      - TZ=Europe/Berlin

  huginn:
    container_name: huginn
    image: huginn/huginn
    restart: unless-stopped
    depends_on: 
      - mariadb
    networks:
      - internal
      - proxy
    environment:
      - TIMEZONE=Berlin
      - DO_NOT_CREATE_DATABASE=true
      - DO_NOT_SEED=true
      - HUGINN_DATABASE_ADAPTER=mysql2
      - HUGINN_DATABASE_HOST=mariadb
      - HUGINN_DATABASE_PORT=3306
      - HUGINN_DATABASE_NAME=huginn_db
      - HUGINN_DATABASE_USERNAME=huginn
      - HUGINN_DATABASE_PASSWORD=..................................
      - SKIP_INVITATION_CODE=true
      - REQUIRE_CONFIRMED_EMAIL=false
    labels:
      - traefik.frontend.rule=Host:huginn.mydomain.xyz
      - traefik.port=3000
      - traefik.docker.network=proxy
      - traefik.protocol=http
```

**Comment by dsander** [comment]
@frumpymoons Try the database variables without the `HUGINN_` prefix, when moving away from the prefix we tried to keep the old ones working as well but we might have broken that somewhere. If you specify an external database the internal mysql server should not be started.

**Comment by frumpymoons** [comment]
@dsander Thanks removing ``` HUGINN_ ``` seems to work.

**Comment by cinghialino** [comment]
can we have PID and GID?

**Comment by dsander** [comment]
@cinghialino Use an external database for that. The internal mysql server is intended for testing purposes.

**Comment by cinghialino** [comment]
Hi @dsander I had problems using an external database, because of permissions. That's the reason I was asking for PID and GUID so the proper user can be set! Maybe I got it all wrong? 
I guess I better read more about it.

**Comment by dsander** [comment]
@cinghialino Sorry I meant to say an external database container. I am using the [postgres](https://hub.docker.com/_/postgres/) image. But `mariadb` should work similarly.

**Comment by kornflex** [comment]
I had to install mysql in version 7, not the latest. mysql 8 not supported yet

And I linked my containers together like this : 

docker run --rm --name huginn_mysql \
    -e MYSQL_DATABASE=huginn \
    -e MYSQL_USER=huginn \
    -e MYSQL_PASSWORD=somethingsecret \
    -e MYSQL_ROOT_PASSWORD=somethingevenmoresecret \
    mysql:7

docker run --rm --name huginn \
    --link huginn_mysql:mysql \
    -p 3000:3000 \
    -e HUGINN_DATABASE_NAME=huginn \
    -e HUGINN_DATABASE_USERNAME=huginn \
    -e HUGINN_DATABASE_PASSWORD=somethingsecret \
    huginn/huginn

**Comment by dsander** [comment]
@kornflex You can use mysql 8 by switching the default authentication plugin:

```
docker run --rm --name huginn_mysql \
  -e MYSQL_DATABASE=huginn \
  -e MYSQL_USER=huginn \
  -e MYSQL_PASSWORD=somethingsecret \
  -e MYSQL_ROOT_PASSWORD=somethingevenmoresecret \
  mysql:8 mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
```

Or use mariadb:

```
docker run --rm --name huginn_mysql \
  -e MYSQL_DATABASE=huginn \
  -e MYSQL_USER=huginn \
  -e MYSQL_PASSWORD=somethingsecret \
  -e MYSQL_ROOT_PASSWORD=somethingevenmoresecret \
  mariadb:10
```

**Comment by MakiG0** [comment]
Hey guys,
i struggled a few days with the same problem and cannot find a solution. 
I used synology nas and a docker-compose for starting huginn with mariadb. The dockers startups correctly and the tables are created in the mariadb. BUT the data will not be stored on external volume both for huginn and the mariadb-docker. Both folders are empty.

I think something with permissions cause the issue.

this is my docker-compose setup for both docker:

 ```
huginndb:
   image: linuxserver/mariadb
   container_name: huginndb
   restart: always
   networks:
     - default
   ports:
     - 4421:3306
   environment:
     - PUID=1035
     - PGID=1035
     - MYSQL_ROOT_PASSWORD=somethingsecret
     - MYSQL_DATABASE=huginn_db
     - MYSQL_USER=huginn
     - MYSQL_PASSWORD=password
     - TZ=Europe/Berlin
   volumes:
     - /volume1/Share/docker-config/huginndb/:/var/lib/mysql
     
  huginn:
    hostname: huginn
    image: huginn/huginn
    container_name: huginn
    links:
     - huginndb
    restart: unless-stopped
    depends_on:
     - huginndb
    networks:
     - traefik_proxy
     - default
    dns:
      - 192.168.178.4
      - 1.1.1.1
    ports:
      - 4422:3000
    environment:
      - DO_NOT_CREAT_DATABASE=true
      - DO_NOT_SEED=true
      #Database configuration
      - DATABASE_ADAPATER=mysql2
      - DATABASE_HOST=huginndb
      - DATABASE_PORT=3306
      - DATABASE_NAME=huginn_db
      - DATABASE_USERNAME=huginn
      - DATABASE_PASSWORD=password
      - DATABASE_ENCODING=utf8mb4
      - OUTDATED_DOCKER_IMAGE_NAMESPACE=false
      #General Configuration
      - INVITATION_CODE=huginn-invitationcode
      - TIMEZONE=Berlin
    volumes:
      - /volume1/Share/docker-config/huginn/:/server/data
```
Anybody got any ideas? Hope somebody can help.

Thanks a lot in advance...
