### ISSUE TITLE
Hugin keeps hanging

### ISSUE THREAD

**Issue by emanuellandell** [huginn/huginn#2662]
Hi,

Any ideas why this happens? I'm using multithreaded Huginn, the exact processes that hangs varies.
What's the best way to kill all running jobs that have been running for longer than 1 hour?

See attached image.

<img width="921" alt="Screenshot 2020-01-08 at 13 13 06" src="https://user-images.githubusercontent.com/9020638/71977373-e4f3ac80-3218-11ea-89f4-88f7933cd310.png">

**Comment by dsander** [comment]
Hey!

I know the irony this implies, but the multi-threaded setup basically isn't thread safe. All is well for most setups, but if a job is taking longer than `DELAYED_JOB_MAX_RUNTIME` it can get process stuck. At this point the job is only shown as running, but it was actually killed by a timeout.

I just realized that we don't even have an example for that, for setups that run have long running jobs regularly I'd recommend running one process for the background jobs and for the scheduler. 

Similar to this https://github.com/huginn/huginn/blob/master/docker/single-process/postgresql.yml

but replacing the `threaded` container with one for delayed_job and one for the `agent_runner.rb`

```
huginn_agent_runner:
...
  command: /scripts/init bin/agent_runner.rb

huginn_dj:
...
  command: /scripts/init script/delayed_job run
```

**Comment by tarek369** [comment]
I have same issue; I use normal docker image and have external db mysql 
any solution ?

**Comment by emanuellandell** [comment]
I had to switch from huginn

**Comment by tarek369** [comment]
What you using now :) ?

**Comment by blissend** [comment]
Yes this keeps happening to me when scrapping certain sites. I use the docker image so can't just restart and have to do the following https://github.com/huginn/huginn/issues/1988#issuecomment-548334831 then restart.

I wish the docker version had more verbose logging or some way to see what it's stuck at short of running strace on the process.

**Comment by cantino** [comment]
@dsander I know this is an old thread, but I think I've been having this same problem. Is this setup safe, or do I need to subdivide it further, perhaps by not using `bin/threaded.rb` at all?

```
huginn:
    image: ghcr.io/huginn/huginn-single-process
    platform: linux/x86_64
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - postgres
    ports:
      - 3001:3000
    links:
      - postgres
    restart: always
    environment:
      - DELAYED_JOB_MAX_RUNTIME=1

  huginn-threaded:
    image: ghcr.io/huginn/huginn-single-process
    platform: linux/x86_64
    command: /scripts/init bin/threaded.rb
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - postgres
      - huginn
    links:
      - postgres
    restart: always
    environment:
      - DELAYED_JOB_MAX_RUNTIME=1
```
