### ISSUE TITLE
Huginn binds to the wrong port (k8s)

### ISSUE THREAD

**Issue by Xaelias** [huginn/huginn#2671]
Hi!
I really like Huginn. But I have a small config issue that I don't really understand at the top of my head (and sadly, don't have the time to investigate on my own right now).
I run Huginn in k8s. And the config looks something like:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: huginn
  namespace: monitoring
spec:
  replicas: 1
    spec:
      containers:
        - name: huginn
          env:
          - name: DOMAIN
            value: "<some_local_fqdn>:3000"
          - name: FORCE_SSL
            value: "false"
          - name: PORT
            value: "3000"
          image: huginnbuilder/huginn:pr-2634
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: huginn
  namespace: monitoring
  labels:
    k8s-app: huginn
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    k8s-app: huginn
```
I removed a lot of cruft that shouldn't be relevant here.
And... the problem is when I just apply this. Huginn overrides the port to be 80 (the service port).
Which is... not what I want. And also just doesn't work because the container doesn't run as privileged so it can't bind on port 80 to begin with.

My workaround so far is to edit the yaml config, set the service port to 3000, start Huginn, then change it back to 80 and re-apply (which only modifies the service).

It works but... it's the first container where I have this issue.
Thanks for the help!
Alexis

**Comment by dsander** [comment]
Sorry I don't know much about Kubernetes, don't you need some kind of ingress to map the port?

Maybe @holmesb or @mariusbuescher is able to help.

@holmesb linked these helm charts https://code.sharkbaitextraordinaire.com/jacob/kube-manifests/src/branch/master/huginn

**Comment by Xaelias** [comment]
That's what the service part is supposed to be. I realized I removed too much from the config.
So the service is supposed to map port 80 (from outside the pod) to port named http defined in the deployment above.
The problem is that somehow, Huginn picks up that, and decides to try and map to port 80.

**Comment by dsander** [comment]
The Huginn container can not influence the port it's internal port is bound to on the host. Comparing your configuration with [this](https://code.sharkbaitextraordinaire.com/jacob/kube-manifests/src/branch/master/huginn/huginn-web-deployment.yaml#L108-L110) makes me think that the `Service` is some sort of kubernetes entity that defines which ports are exposed by a pod(?!?). I am pretty certain that you need a Ingress like [this](https://code.sharkbaitextraordinaire.com/jacob/kube-manifests/src/branch/master/huginn/huginn-web-ingress.yaml) to expose the service externally.

**Comment by Xaelias** [comment]
Ingress is a totally different use case.
I just have a dumb service: https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service
That is supposed to route port 80 on the service endpoint, to port http (defined as 3000 in this case) on any pod that matches the selector (k8s-app == huginn).

This actually works. The problem is there is something in the wiring that makes Huginn believes that I'm asking it to bind to port 80 when I do that. It's the first time this happened to me. I have a very similar setup for grafana for instance, that doesn't behaves the same at all.

**Comment by dsander** [comment]
Aren't you telling kubernetes to use port 80 with that section?
```yaml

spec:
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    k8s-app: huginn
```

Like I said before we don't have any way to define or override to host/external port to which our internal port `3000` is mapped to.

I have no idea how kubernetes services work, but how about you try to change port `90` to `3000` in the service definition?

**Comment by Xaelias** [comment]
I'm not claiming to be an expert. But no. What this is supposed to be doing is create a service (basically just a routing layer) that routes port 80 on that service endpoint to port 3000 on that pod.
That service is technically not tied to the deployment. It could be defined in a different yaml file.

**Comment by dsander** [comment]
> For some reason, huginn tries to bind to port 80 inside the container and ignore the environment variables.

I think https://github.com/huginn/huginn/pull/2112#discussion_r137075363 might be happening here. Can you attach to the running pod and paste the output of `env`? If it's really caused by the `HUGINN_PORT` environment variable set by kubernetes you can probably work around it by calling your deployment something else than `huginn`.

**Comment by Xaelias** [comment]
I've been swamped but yeah my next step was to go look at env variables in the pod itself.
I assume something overrides the wrong thing or whatever.
I'll check when I have time :-)
Thanks!

**Comment by holmesb** [comment]
I've got Huginn working in k8s (the webui is up).  I just set all ports in pod and service to 3000.

**Comment by Xaelias** [comment]
> I've got Huginn working in k8s (the webui is up). I just set all ports in pod and service to 3000.

That's kind of missing the point of what I'm trying to do here though :-D

Sorry it took me so long to get back here ><
So this is the the values that change between the working version but hacked manually (have to modify the service mid run) and the version that fails to start because it tries to bind to port 80.
```
HUGINN_PORT=tcp://10.201.149.103:3000
HUGINN_PORT_3000_TCP=tcp://10.201.149.103:3000
HUGINN_PORT_3000_TCP_ADDR=10.201.149.103
HUGINN_PORT_3000_TCP_PORT=3000
HUGINN_PORT_3000_TCP_PROTO=tcp
HUGINN_SERVICE_HOST=10.201.149.103
HUGINN_SERVICE_PORT=3000
HUGINN_SERVICE_PORT_HTTP=3000
```
vs
```
HUGINN_PORT=tcp://10.201.53.47:80
HUGINN_PORT_80_TCP=tcp://10.201.53.47:80
HUGINN_PORT_80_TCP_ADDR=10.201.53.47
HUGINN_PORT_80_TCP_PORT=80
HUGINN_PORT_80_TCP_PROTO=tcp
HUGINN_SERVICE_HOST=10.201.53.47
HUGINN_SERVICE_PORT=80
HUGINN_SERVICE_PORT_HTTP=80
```
I have to admit I'm not sure which ones come from k8s (well the SERVICE ones at least) but...

**Comment by dsander** [comment]
Have you tried renaming your service to something like `huginn2`? I am pretty certain that k8s generates the `SERVICENAME_PORT` variables which confuse our the Huginn docker container.

**Comment by Xaelias** [comment]
```
env | grep HUGINNN
HUGINNNNN_PORT_80_TCP_PORT=80
HUGINNNNN_SERVICE_HOST=10.201.164.178
HUGINNNNN_PORT_80_TCP=tcp://10.201.164.178:80
HUGINNNNN_SERVICE_PORT=80
HUGINNNNN_PORT_80_TCP_PROTO=tcp
HUGINNNNN_SERVICE_PORT_HTTP=80
HUGINNNNN_PORT_80_TCP_ADDR=10.201.164.178
HUGINNNNN_PORT=tcp://10.201.164.178:80
```
So yeah all of these are from the service.

Turns out, since 1.13, there is a way to disable that behavior (that from quick reading seem to be basically not useful in the first place these days either way).

So following: https://github.com/kubernetes/kubernetes/pull/68754

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: huginn
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: huginn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: huginn
    spec:
      enableServiceLinks: false
```
etc. etc.

Thanks for bearing with me and helping me figure this out :-)
I really appreciate it.
