### ISSUE TITLE
Create a new postgres schema on load

### ISSUE THREAD

**Issue by Nahums0** [huginn/huginn#3125]
I want to connect to a postgres db and work in a seperate schema than the default, I managed to do so by adding the "schema_search_path" setting to the database.yml file
Problem is if the schema doesn't exist it doesn't create it 
Is anyone aware of a way to make huginn create the postgres schema if it doesn't exist? 

The database.yml change - will try to create a PR for this later
```
production:
  adapter: <%= ENV['DATABASE_ADAPTER'].presence || "mysql2" %>
  encoding: <%= ENV['DATABASE_ENCODING'].presence || "utf8" %>
  reconnect: <%= ENV['DATABASE_RECONNECT'].presence || "true" %>
  database: <%= ENV['DATABASE_NAME'].presence || "huginn_production" %>
  pool: <%= ENV['DATABASE_POOL'].presence || "20" %>
  username: <%= ENV['DATABASE_USERNAME'].presence || "root" %>
  password: <%= ENV['DATABASE_PASSWORD'].presence || "password" %>
  host: <%= ENV['DATABASE_HOST'] || "" %>
  port: <%= ENV['DATABASE_PORT'] || "" %>
  socket: <%= ENV['DATABASE_SOCKET'] || ["/var/run/mysqld/mysqld.sock", "/opt/local/var/run/mysql5/mysqld.sock", "/tmp/mysql.sock"].find{ |path| File.exist? path } %>
  strict: false
  schema_search_path: <%= ENV['POSTGRES_SCHEMA'] || "public" %>
```

Thanks.
