### ISSUE TITLE
Git error unsafe repository

### ISSUE THREAD

**Issue by RobHooper** [huginn/huginn#3147]
Following an update in `git` earlier this year, Huginn logs a number of git permissions warnings while booting up:

> foreman stderr | fatal: unsafe repository ('/app' is owned by someone else)
> To add an exception for this directory, call:
>         git config --global --add safe.directory /app

I believe the problem is that the git directories are owned by the `root` user but foreman is running as the user `default`.

**Comment by viharm** [comment]
I am observing the same error.

**Comment by rndph** [comment]
The same issue can be observed using the [latest `huginn/huginn-single-process`](https://hub.docker.com/layers/huginn/huginn-single-process/latest/images/sha256-0a4f88049ebe7b429ea6cc4615e425c75d39db59af6bd6ec48a2371d462e83c3?context=explore)

```
huginn         | fatal: unsafe repository ('/app' is owned by someone else)
huginn         | To add an exception for this directory, call:
huginn         | 
huginn         |        git config --global --add safe.directory /app
```

<details>
<summary>Here is my compose.yaml for docker compose:</summary>

```yaml
services:
  huginn:
    image: huginn/huginn-single-process
    container_name: huginn
    restart: unless-stopped
    networks:
      - traefik
      - mysql
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.huginn.rule=Host(`huginn.mydomain.com`)"
      - "traefik.http.routers.huginn.middlewares=home-ip-only@file"
  huginn-worker:
    image: huginn/huginn-single-process
    container_name: huginn_worker
    command: '/scripts/init bin/threaded.rb'
    restart: unless-stopped
    depends_on:
      - huginn
    networks:
      - mysql
    env_file:
      - ./.env
networks:
  traefik:
    external: true
  mysql:
    external: true
```

</details>

(There are also lots of `/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated` warnings, but those should be solved in another issue.)
