### ISSUE TITLE
Trouble setting Huginn up w/ Docker & Caddy

### ISSUE THREAD

**Issue by alexcochran** [huginn/huginn#3313]
Howdy,

I've been trying to install Huginn on a VPS ([via Kamatera](https://www.kamatera.com/)).  After some troubleshooting, I ended up adapting the `docker-compose.yml` found in this [article](https://zblesk.net/blog/running-huginn-with-docker/) and following the same steps the author did to create a Huginn table in the MariaDB conainer. I also want to use [Caddy](https://caddyserver.com/) as a reverse proxy.

## Current Setup

`docker-compose.yml`
```
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DATA_FOLDER}/caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - huginn_network

  mariadb:
    image: mariadb
    deploy:
      restart_policy:
        condition: any
    ports:
      - "3306:3306"
    networks:
      - huginn_network
    environment:
      - MYSQL_ROOT_PASSWORD=************
    volumes:
      - "mariadb_data:/var/lib/mysql"

  huginn:
    image: huginn/huginn
    deploy:
      restart_policy:
        condition: any
    networks:
      - huginn_network
    ports:
      - "3000:3000"
    depends_on:
      - "mariadb"
    environment:
    - SMTP_DOMAIN=smtp.mailgun.org
    - SMTP_USER_NAME=my@mailgun.user
    - SMTP_PASSWORD=smtpPassword
    - SMTP_SERVER=smtp.mailgun.org
    - APP_SECRET_TOKEN=************
    - DOMAIN=************
    - DATABASE_ADAPTER=mysql2
    - DATABASE_ENCODING=utf8mb4
    - DATABASE_RECONNECT=true
    - DATABASE_NAME=huginn
    - DATABASE_POOL=20
    - DATABASE_USERNAME=huginn
    - DATABASE_PASSWORD=************
    - DATABASE_HOST=mariadb
    - DATABASE_PORT=3306
    - DO_NOT_SEED=true
    - EMAIL_FROM_ADDRESS=from@mydomain.com
    - INVITATION_CODE=************
    - REMEMBER_FOR=40.weeks
    - IMPORT_DEFAULT_SCENARIO_FOR_ALL_USERS=false
    - USE_GRAPHVIZ_DOT=dot
    - TIMEZONE=************

networks:
  huginn_network:

volumes:
  caddy_data:
    external: true
  caddy_config:
  mariadb_data:

```

## Connection Error

When I go to the address of my Huginn service in the browser, I get the following:

```
{
    "level": "error",
    "ts": 1693929490.3686452,
    "logger": "http.log.error",
    "msg": "dial tcp 172.19.0.4:3000: connect: connection refused",
    "request": {
        "remote_ip": "************",
        "remote_port": "*****",
        "client_ip": "************",
        "proto": "HTTP/2.0",
        "method": "GET",
        "host": "huginn.mydomain.com",
        "uri": "/",
        "headers": {
            "Cache-Control": [
                "max-age=0"
            ],
            "Upgrade-Insecure-Requests": [
                "1"
            ],
            "Sec-Fetch-Mode": [
                "navigate"
            ],
            "Accept-Language": [
                "en-US,en;q=0.7"
            ],
            "Sec-Fetch-User": [
                "?1"
            ],
            "Accept-Encoding": [
                "gzip, deflate, br"
            ],
            "Sec-Ch-Ua-Mobile": [
                "?0"
            ],
            "User-Agent": [
                "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
            ],
            "Accept": [
                "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
            ],
            "Cookie": [],
            "Sec-Ch-Ua": [
                "\"Not/A)Brand\";v=\"99\", \"Brave\";v=\"115\", \"Chromium\";v=\"115\""
            ],
            "Sec-Fetch-Site": [
                "cross-site"
            ],
            "Sec-Fetch-Dest": [
                "document"
            ],
            "Sec-Ch-Ua-Platform": [
                "\"Linux\""
            ],
            "Sec-Gpc": [
                "1"
            ]
        },
        "tls": {
            "resumed": false,
            "version": 772,
            "cipher_suite": 4865,
            "proto": "h2",
            "server_name": "huginn.mydomain.com"
        }
    },
    "duration": 0.001855477,
    "status": 502,
    "err_id": "aa5uqtvct",
    "err_trace": "reverseproxy.statusError (reverseproxy.go:1248)"
}
```

How can I achieve hosting Huginn with Caddy as my reverse proxy?

**Comment by alexcochran** [comment]
**Update:** I figured it out. It was some combination of fixing the network setup in my compose file and updating my Caddyfile back from an incorrect change made earlier. I also updated the Huginn image to use the GHCR version.

`docker-compose.yml`
```
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DATA_FOLDER}/caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - huginn_network

  mariadb:
    image: mariadb
    deploy:
      restart_policy:
        condition: any
    ports:
      - "3306:3306"
    networks:
      - huginn_network
    environment:
      - MYSQL_ROOT_PASSWORD=************
    volumes:
      - "mariadb_data:/var/lib/mysql"

  huginn:
    image: ghcr.io/huginn/huginn
    deploy:
      restart_policy:
        condition: any
    networks:
      - huginn_network
    ports:
      - "3000:3000"
    depends_on:
      - "mariadb"
    environment:
    - SMTP_DOMAIN=smtp.mailgun.org
    - SMTP_USER_NAME=my@mailgun.user
    - SMTP_PASSWORD=smtpPassword
    - SMTP_SERVER=smtp.mailgun.org
    - APP_SECRET_TOKEN=************
    - DOMAIN=************
    - DATABASE_ADAPTER=mysql2
    - DATABASE_ENCODING=utf8mb4
    - DATABASE_RECONNECT=true
    - DATABASE_NAME=huginn
    - DATABASE_POOL=20
    - DATABASE_USERNAME=huginn
    - DATABASE_PASSWORD=************
    - DATABASE_HOST=mariadb
    - DATABASE_PORT=3306
    - DO_NOT_SEED=true
    - EMAIL_FROM_ADDRESS=from@mydomain.com
    - INVITATION_CODE=************
    - REMEMBER_FOR=40.weeks
    - IMPORT_DEFAULT_SCENARIO_FOR_ALL_USERS=false
    - USE_GRAPHVIZ_DOT=dot
    - TIMEZONE=************

networks:
  huginn_network:
    external: true

volumes:
  caddy_data:
    external: true
  caddy_config:
  mariadb_data:
```

`caddy_config/Caddyfile`
```
huginn.mydomain.com {
    reverse_proxy huginn:3000 {
      flush_interval -1
    }
}
```
