### ISSUE TITLE
Docker: Failed to register layer

### ISSUE THREAD

**Issue by Kamiikaze** [huginn/huginn#3351]
## Enviroment
Promox LXC
```yaml
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: zfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.126-1-pve
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 4GiB
 Name: Docker
 ID: d245dcbe-33f7-4398-8e66-de1eab63f245
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
## Issue
Cant't pull the image. Always getting the following error:

```bash
docker run -it -p 3000:3000 -v /home/huginn/mysql-data:/var/lib/mysql huginn/huginn
Unable to find image 'huginn/huginn:latest' locally
latest: Pulling from huginn/huginn
2ab09b027e7f: Already exists 
234c8a12fd0f: Pull complete 
fd8d6c82661d: Pull complete 
4f4fb700ef54: Pull complete 
185725d1c187: Pull complete 
e0232f33baed: Pull complete 
96974ca220be: Pull complete 
1bfd9afa7b73: Pull complete 
a58989011754: Pull complete 
695d90d833e0: Pull complete 
070190d2f575: Pull complete 
dc43042a683c: Pull complete 
1fbc814fd80b: Pull complete 
848114973c12: Extracting [==================================================>]  193.1MB/193.1MB
cae4f14cb6cf: Download complete 
8a46c2b46b69: Download complete 
da45103f4f04: Download complete 
94848ff0715a: Download complete 
53c04079e216: Download complete 
84fcfd5b5dfd: Download complete 
7040720bb7a1: Download complete 
3bec8e2643d6: Download complete 
22c379c87cde: Download complete 
46d38e7188d3: Download complete 
8b1b00bfc880: Download complete 
702dd3a0902c: Download complete 
4f64c833249e: Download complete 
b0482694497d: Download complete 
f5e2c3e8c110: Download complete 
docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /usr/share/doc/bash: invalid argument.
See 'docker run --help'.
```
