### ISSUE TITLE
Huginn crashes when  TIMEZONE=Europe/something env.var is set

### ISSUE THREAD

**Issue by bogorad** [huginn/huginn#3483]
About a month ago I added a TIMEZONE= env.var in the same format as TZ=. Just noticed that taskes stopped running. Removed it and it works again. Still a bug.

```
HuginnScheduler
/app/lib/huginn_scheduler.rb:141:in `+': no implicit conversion of nil into String (TypeError)
      cron "0 #{hour} * * * " + tzinfo_friendly_timezone do
                                ^^^^^^^^^^^^^^^^^^^^^^^^
	from /app/lib/huginn_scheduler.rb:141:in `block in setup'
	from /app/lib/huginn_scheduler.rb:140:in `times'
	from /app/lib/huginn_scheduler.rb:140:in `setup'
	from /app/app/concerns/long_runnable.rb:86:in `setup!'
	from /app/lib/agent_runner.rb:82:in `block in run_workers'
	from /app/lib/agent_runner.rb:79:in `each'
	from /app/lib/agent_runner.rb:79:in `run_workers'
	from /app/lib/agent_runner.rb:39:in `run'
	from bin/threaded.rb:13:in `<main>'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.10/lib/rails/commands/runner/runner_command.rb:42:in `load'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.10/lib/rails/commands/runner/runner_command.rb:42:in `perform'
	from /app/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
	from /app/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /app/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.10/lib/rails/command/base.rb:69:in `perform'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.10/lib/rails/command.rb:48:in `invoke'
	from /app/vendor/bundle/ruby/3.2.0/gems/railties-6.1.7.10/lib/rails/commands.rb:18:in `<main>'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /app/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:9:in `<main>'
```

**Comment by bogorad** [comment]
absolutely, I just duplicated the TZ line:

```
  huginn_threaded:
    image: ghcr.io/huginn/huginn-single-process
    container_name: huginn_threaded
    command: /scripts/init bin/threaded.rb
    restart: always
    environment:
      - TZ=Europe/Madrid
      # - TIMEZONE=Europe/Madrid
...
```
