### ISSUE TITLE
[help wanted] trying to connect to gmail

### ISSUE THREAD

**Issue by kazimurtaza** [huginn/huginn#3488]
Hi, I have tried a lot but cannot seem to connect to my account,
I even tried disabling 2fa, but I still keep getting
535-5.7.8 Username and Password not accepted. For more information, go to

```
version: '3.5'
services:
  huginn:
    image: ghcr.io/huginn/huginn
    restart: always
    ports:
      - 4750:3000
    environment:
      - SMTP_DOMAIN="smtp.gmail.com"
      - SMTP_SERVER="smtp.gmail.com"
      - SMTP_USER_NAME=""
      - SMTP_PASSWORD=""
      - EMAIL_FROM_ADDRESS=""
      - TIMEZONE="Australia/Melbourne"

```
